### PR TITLE
Build a dynamic library to enable integration with third-party applications.

### PR DESCRIPTION
**Pull request by pspoerri**

### CODE REVIEW

**Review by BernardMetzler — COMMENTED** [review]
nice and needed! 

can't we stick with 'libgeds' or some-such naming scheme? I am very used to libs starting with 'lib' ;)

**Comment by pspoerri** [comment]
I understand the confusion. CMake will automatically prepend a library with `lib`.

Let me explain: In this PR I first create a virtual library that acts as a compile-target for the individual objects (`geds_objlib`). I then link the external dependencies (absl, boost, curl, etc...) with this compile target.
Finally, I tell CMake to build two libraries: `libgeds` and `libgeds_dynamic`. These are just internal names, since I'm both renaming the output of these libraries to `geds`. This rename then results in two libraries which are called:

- `libgeds.a`
- `libgeds.so`

The `libgeds_dynamic`-target is only used to create `libgeds.so`. `libgeds` itself is used as a dependency for the other products. There's already a CMake `geds` target which is a command line tool ( https://github.com/IBM/GEDS/blob/main/src/geds/CMakeLists.txt ) - which is why I need to rename the output of `libgeds`.

**Comment by pspoerri** [comment]
`add_library(libgeds STATIC ${SOURCES})` will create a library which is called `liblibgeds.a`.

**Comment by BernardMetzler** [comment]
great explanation, thanks!

From: Pascal Spörri ***@***.***>
Sent: Wednesday, 15 February 2023 16:13
To: IBM/GEDS ***@***.***>
Cc: Bernard Metzler ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [IBM/GEDS] Build a dynamic library to enable integration with third-party applications. (PR #16)

I understand the confusion. CMake will automatically prepend a library with lib. Let me explain: In this PR I first create a virtual library that acts as a compile-target for the individual objects (geds_objlib). I then link the external dependencies
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

I understand the confusion. CMake will automatically prepend a library with lib.

Let me explain: In this PR I first create a virtual library that acts as a compile-target for the individual objects (geds_objlib). I then link the external dependencies (absl, boost, curl, etc...) with this compile target.
Finally, I tell CMake to build two libraries: libgeds and libgeds_dynamic. These are just internal names, since I'm both renaming the output of these libraries to geds. This rename then results in two libraries which are called:

  *   libgeds.a
  *   libgeds.so

The libgeds_dynamic-target is only used to create libgeds.so. libgeds itself is used as a dependency for the other products. There's already a CMake geds target which is a command line tool ( https://github.com/IBM/GEDS/blob/main/src/geds/CMakeLists.txt<https://github.com/IBM/GEDS/blob/main/src/geds/CMakeLists.txt> ) - which is why I need to rename the output of libgeds.

**Pull request merged**
